ORG &8000 		;INDIRIZZO DI MEMORIA ORIGINE DEL PROGRAMMA
	LD A, 4		;A = 4
	INC A		;A = 5
	INC A		;A = 6
	LD B, 10	;B = 10
	ADD B		;SOMMA IL VALORE DI A CON IL VALORE DI B E LO INSERISCE IN A
	LD (&8200), A	;IL VALORE DI A (16) E' ADESSO PRESENTE NELL'INDIRIZZO 8200
RET			;USCITA DAL PROGRAMMA